### ISSUE TITLE
Add tests, contributing guidelines and coverage report

### ISSUE THREAD

**Issue by mavogel** [dbsystel/kibana-config-controller#2]
- [ ] add tests (testify and mockery. See base line [here](https://tutorialedge.net/golang/improving-your-tests-with-testify-go/))
- [ ] refactor code
- [ ] remove `dupl` and other rules from `lint` target
- [ ] add code coverage report to PRs
- [ ] add contribution guidelines

**Comment by dbluxo** [comment]
will be done separately
